// GET METHOD
export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

// POST METHOD
export const POST_PRODUCT_PROGRESS = "POST_PRODUCT_PROGRESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";
