// get product
export const GET_PRODUCT_PROGRESS = "GET_PRODUCT_PROGRESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

//post product
export const POST_PRODUCT_PROGRESS = "POST_PRODUCT_PROGRESS";
export const POST_PRODUCT_SUCCESS = "POST_PRODUCT_SUCCESS";
export const POST_PRODUCT_ERROR = "POST_PRODUCT_ERROR";

// delete product
export const DELETE_PRODUCT_PROGRESS = "DELETE_PRODUCT_PROGRESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

//update product
export const PUT_PRODUCT_PROGRESS = "PUT_PRODUCT_PROGRESS";
export const PUT_PRODUCT_SUCCESS = "PUT_PRODUCT_SUCCESS";
export const PUT_PRODUCT_ERROR = "PUT_PRODUCT_ERROR";
