// GET PRODUCT
export const GET_USER_PRODUCT_SUCCESS = "GET_USER_PRODUCT_SUCCESS";
export const GET_USER_PRODUCT_ERROR = "GET_USER_PRODUCT_ERROR";
export const GET_USER_PRODUCT_PROGRESS = "GET_USER_PRODUCT_PROGRESS";

// POST PRODUCT
export const POST_USER_PRODUCT_SUCCESS = "POST_USER_PRODUCT_SUCCESS";
export const POST_USER_PRODUCT_ERROR = "POST_USER_PRODUCT_ERROR";
export const POST_USER_PRODUCT_PROGRESS = "POST_USER_PRODUCT_PROGRESS";

// DELETE PRODUCT
export const DELETE_USER_PRODUCT_SUCCESS = "DELETE_USER_PRODUCT_SUCCESS";
export const DELETE_USER_PRODUCT_ERROR = "DELETE_USER_PRODUCT_ERROR";
export const DELETE_USER_PRODUCT_PROGRESS = "DELETE_USER_PRODUCT_PROGRESS";

// UPDATE PRODUCT
export const PUT_USER_PRODUCT_SUCCESS = "PUT_USER_PRODUCT_SUCCESS";
export const PUT_USER_PRODUCT_ERROR = "PUT_USER_PRODUCT_ERROR";
export const PUT_USER_PRODUCT_PROGRESS = "PUT_USER_PRODUCT_PROGRESS";